services:
  backend:
    build: ./device-management-backend
    ports:
      - "8000:8000"
  
  frontend:
    build: ./device-management-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
